project_id = "qulhweffinppyjpfkknh"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.dev"]

[functions.google-directions]
verify_jwt = true

[functions.get-google-maps-key]
verify_jwt = true

[functions.check-expirations]
verify_jwt = false

[functions.renovar-timbres-mensuales]
verify_jwt = false

[functions.consume-credit]
verify_jwt = true

[functions.sanitize-logs-cron]
verify_jwt = false

[functions.validate-csrf]
verify_jwt = true

[functions.timbrar-con-sw]
verify_jwt = true

[functions.consultar-rfc-sat]
verify_jwt = true

[functions.generar-pdf-factura]
verify_jwt = true

[functions.timbrar-carta-porte]
verify_jwt = true
